name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to AWS
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@44.240.11.43 'echo "hello world"'

runs-on: self-hosted